[project]
name = "28-computer-use"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    #"google-generativeai>=0.8.5",
    "ipython>=9.6.0",
    "google-genai",
    "playwright"
]
